#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'r1-camera-viewer==0.1.0','console_scripts','camera_viewer'
__requires__ = 'r1-camera-viewer==0.1.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('r1-camera-viewer==0.1.0', 'console_scripts', 'camera_viewer')()
    )
